/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'question' : IDL.Text,
  'user' : IDL.Principal,
  'response' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Score = IDL.Record({
  'user' : IDL.Principal,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'getUserChatHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getUserScores' : IDL.Func([IDL.Principal], [Score], ['query']),
  'submitScore' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({
    'question' : IDL.Text,
    'user' : IDL.Principal,
    'response' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Score = IDL.Record({
    'user' : IDL.Principal,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllScores' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'getUserChatHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getUserScores' : IDL.Func([IDL.Principal], [Score], ['query']),
    'submitScore' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };